// <auto-generated />
using System;
using Goomer_Lista_Rango;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Goomer_Lista_Rango.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20220712220722_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Goomer_Lista_Rango.Data.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Goomer_Lista_Rango.Data.Discount", b =>
                {
                    b.Property<int>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("DiscountPrice")
                        .HasColumnType("double");

                    b.HasKey("DiscountId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("Goomer_Lista_Rango.Data.OpenHour", b =>
                {
                    b.Property<int>("OpenHourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("OpenHourId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("OpenHours");
                });

            modelBuilder.Entity("Goomer_Lista_Rango.Data.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("ProductPhoto")
                        .HasColumnType("longtext");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Goomer_Lista_Rango.Data.Promotion", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PromotionBegins")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PromotionDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PromotionEnds")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ProductId", "DiscountId");

                    b.HasIndex("DiscountId");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("Goomer_Lista_Rango.Data.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RestaurantPhoto")
                        .HasColumnType("longtext");

                    b.HasKey("RestaurantId");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("Goomer_Lista_Rango.Data.OpenHour", b =>
                {
                    b.HasOne("Goomer_Lista_Rango.Data.Restaurant", "Restaurant")
                        .WithMany("OpenHours")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Goomer_Lista_Rango.Data.Product", b =>
                {
                    b.HasOne("Goomer_Lista_Rango.Data.Restaurant", "Restaurant")
                        .WithMany("Products")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("Goomer_Lista_Rango.Data.Promotion", b =>
                {
                    b.HasOne("Goomer_Lista_Rango.Data.Discount", "Discount")
                        .WithMany("Promotions")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Goomer_Lista_Rango.Data.Product", "Product")
                        .WithMany("Promotions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Goomer_Lista_Rango.Data.Restaurant", b =>
                {
                    b.HasOne("Goomer_Lista_Rango.Data.Address", "Address")
                        .WithOne("Restaurant")
                        .HasForeignKey("Goomer_Lista_Rango.Data.Restaurant", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Goomer_Lista_Rango.Data.Address", b =>
                {
                    b.Navigation("Restaurant")
                        .IsRequired();
                });

            modelBuilder.Entity("Goomer_Lista_Rango.Data.Discount", b =>
                {
                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("Goomer_Lista_Rango.Data.Product", b =>
                {
                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("Goomer_Lista_Rango.Data.Restaurant", b =>
                {
                    b.Navigation("OpenHours");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
